project_id = "gguvapwqyuxaydmcrfgt"

[functions.validate-invite-code]
verify_jwt = false

[functions.use-invite-code]
verify_jwt = false

[functions.google-drive-auth]
verify_jwt = false

[functions.google-drive-token]
verify_jwt = false

[functions.google-drive-disconnect]
verify_jwt = false

[functions.parse-mcq-text]
verify_jwt = false

[functions.parse-mcq-pdf]
verify_jwt = false
